//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP2184587.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_compra
    {
        public int id { get; set; }
        public Nullable<int> id_compra { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual producto producto { get; set; }
    }
}
